### ISSUE TITLE
Snapping window to top extends window beyond screen

### ISSUE THREAD

**Issue by ZonK256** [newbiedeveloper9/sharpdj#14]
Snapping window to top extends window beyond screen. Also, the program won't recognize snapping as "extending window to full screen" and after clicking Maximize button, program resize window to full screen (this time properly).

**Comment by wojciechowskiapp** [comment]
https://github.com/newbiedeveloper9/sharpdj/commit/f3d45bf3bc39f92c85f0f62b19792b86463f383b
